# Generated by Django 4.0.6 on 2022-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_areanews_news_areanoticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='areaNoticia',
        ),
        migrations.AddField(
            model_name='news',
            name='areaNews',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_area', to='news.areanews', verbose_name='Area'),
        ),
    ]
