# Generated by Django 4.0.6 on 2022-08-19 21:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='linkPlanMaterias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Plan de Estudio'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='linkRegimenCursada',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Régimen de Cursada'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='planMaterias',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nombre de Plan de Materias'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='turnos',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Turnos'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo'),
        ),
    ]
