# Generated by Django 4.0.6 on 2022-08-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_carrera_linkplanmaterias_carrera_linkregimencursada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='planMaterias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Plan de Estudio'),
        ),
    ]
