# Generated by Django 4.0.6 on 2022-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_alter_carrera_planmaterias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='planMaterias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título Plan de Estudio'),
        ),
    ]
