# Generated by Django 4.0.6 on 2022-08-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0004_alter_carrera_planmaterias'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='bannerCarrera',
            field=models.ImageField(blank=True, null=True, upload_to='carreras', verbose_name='Banner de Carrera'),
        ),
    ]
